import {describe,expect,it,vi} from 'vitest';
import {assertSingleThumbnail,SINGLE_THUMBNAIL as S} from '../single-thumbnail-policy';
import {preserveOne,type Receipt,type PreservationPorts} from '../preserve-english-finals';
import {DriveClient} from '../../../packages/storage/src/drive/client';
import {loadStorageConfig} from '../../../packages/storage/src/config';
const input={...S,completedAt:'2026-09-09T00:00:00Z',mimeType:'image/jpeg',statToken:'synthetic'};
const file={jobId:S.jobId,path:'/private/spool',sourceRevision:S.sourceRevision,completedAt:input.completedAt,bytes:S.bytes,sha256:S.sha256,md5:S.md5,statToken:'synthetic'};
function ports(){const history:Receipt[]=[],start=vi.fn(async()=> 'https://www.googleapis.com/upload/drive/v3/files?upload_id=synthetic');const p:PreservationPorts={recheck:async()=>{},find:async()=>null,start,offset:async()=>0,chunk:async()=>({fileId:'synthetic-id'}),verify:async()=>{},append:async row=>{history.push(row)}};return{history,start,p};}
describe('fixed singleton thumbnail preservation',()=>{
  it('accepts only reviewed thumbnail identity, byte size and digests',()=>{expect(()=>assertSingleThumbnail(input)).not.toThrow();for(const change of [{thumbnailId:'other'},{jobId:'other'},{bytes:146124},{sha256:'a'.repeat(64)},{sourceRevision:'b'.repeat(64)},{mimeType:'video/mp4'}])expect(()=>assertSingleThumbnail({...input,...change})).toThrow()});
  it('lost create response persists intent and cannot blindly create on retry',async()=>{const f=ports();f.start.mockRejectedValue(Error('lost create response'));await expect(preserveOne(file,f.history,f.p)).rejects.toThrow();expect(f.history.map(r=>r.stage)).toEqual(['intent']);f.start.mockClear();await expect(preserveOne(file,f.history,f.p)).rejects.toThrow('reconciliation');expect(f.start).not.toHaveBeenCalled()});
  it('failed ledger fsync stops before any remote create',async()=>{const f=ports();f.p.append=async()=>{throw Error('fsync failed')};await expect(preserveOne(file,[],f.p)).rejects.toThrow();expect(f.start).not.toHaveBeenCalled()});
  it('source selection change after readback never emits verified',async()=>{const f=ports();let checks=0;f.p.recheck=async()=>{if(++checks===3)throw Error('source selection changed')};await expect(preserveOne(file,f.history,f.p)).rejects.toThrow();expect(f.history.some(r=>r.stage==='uploaded')).toBe(true);expect(f.history.some(r=>r.stage==='verified')).toBe(false)});
  it('actual Drive client configured with one attempt never retries ambiguous create',async()=>{const loaded=loadStorageConfig({STORAGE_DRIVE_ENABLED:'true',GOOGLE_DRIVE_CLIENT_ID:'test',GOOGLE_DRIVE_CLIENT_SECRET:'test',GOOGLE_DRIVE_REFRESH_TOKEN:'test'});if(!loaded.enabled)throw Error('fixture');loaded.drive.maxAttempts=1;let creates=0;const fake:typeof fetch=async(url)=>{if(String(url).includes('oauth2.googleapis.com'))return new Response(JSON.stringify({access_token:'synthetic',expires_in:3600}),{status:200});creates++;throw Error('connection lost')};const client=new DriveClient(loaded.drive,{fetch:fake});const r=await client.createResumableSession({filename:'synthetic.jpg',parentId:S.folderId,mimeType:'image/jpeg',sizeBytes:S.bytes,jobId:S.jobId,kind:'thumbnail',sourceSha256:S.sha256});expect(r.ok).toBe(false);expect(creates).toBe(1)});
});
