import {afterEach,describe,expect,it,vi} from 'vitest';
const f=vi.hoisted(()=>({db:null as any}));vi.mock('node:module',()=>({createRequire:()=>()=>()=>f.db}));
import {promoteSingleThumbnail} from '../single-thumbnail-promotion-transaction';
import {SINGLE_THUMBNAIL as S} from '../single-thumbnail-policy';
const original=Object.getOwnPropertyDescriptor(process,'getuid');afterEach(()=>{if(original)Object.defineProperty(process,'getuid',original);else delete(process as any).getuid});
function fixture(){const calls:string[]=[],db:any=async(parts:TemplateStringsArray)=>{calls.push(parts.join('?'));return[{db:'tutorial_staging_cf_20260908',role:'tutorial_staging',fresh:true,result:{parentInserts:1,versionInserts:1,pointerUpdates:1}}]};db.unsafe=async(s:string)=>{calls.push(s)};db.end=async()=>calls.push('END');f.db=db;Object.defineProperty(process,'getuid',{configurable:true,value:()=>1000});const plan={job:{id:S.jobId},thumbnail:{id:S.thumbnailId},version:{bytes:S.bytes,checksum_sha256:S.sha256,drive_file_id:'1S5yw7OnPaJ0kgjwiHJo7yn2SjVhLrXmZ'},localEntries:[],localSnapshots:[]};return{calls,db,plan};}
describe('singleton SQL guards',()=>{
 it('defaults rollback and takes root then thumbnail then media then artifact fences',async()=>{const s=fixture(),r=await promoteSingleThumbnail(s.plan,async()=>[]);expect(r.committedWrites).toBe(0);expect(s.calls.at(-2)).toBe('ROLLBACK');const q=s.calls.find(x=>x.includes('root_cas'))!;expect(q.indexOf('FROM tutorial_jobs')).toBeLessThan(q.indexOf('FROM thumbnails'));expect(q.indexOf('FROM thumbnails')).toBeLessThan(q.indexOf('tutorial-media:'));expect(q.indexOf('tutorial-media:')).toBeLessThan(q.indexOf('FROM storage_artifacts'))});
 it('requires protected backup for explicit commit and aborts changed local state',async()=>{const s=fixture();await expect(promoteSingleThumbnail(s.plan,async()=>[],'commit-single-thumbnail')).rejects.toThrow('backup');await expect(promoteSingleThumbnail(s.plan,async()=>[{changed:true}])).rejects.toThrow('local_fence');expect(s.calls).not.toContain('COMMIT')});
 it('lost COMMIT ACK remains uncertain, not a reported rollback (mock only)',async()=>{const s=fixture();s.db.unsafe=async(q:string)=>{s.calls.push(q);if(q==='COMMIT')throw Error('lost ack')};const backup={database:'tutorial_staging_cf_20260908',listingVerified:true,bytes:123,sha256:'a'.repeat(64),path:'/var/tmp/tutorial-preservation-promotion-synthetic/staging-before-promotion.dump',completedAt:'2026-09-09T00:00:00Z'};await expect(promoteSingleThumbnail(s.plan,async()=>[],'commit-single-thumbnail',backup)).rejects.toThrow('uncertain');expect(s.calls).not.toContain('ROLLBACK')});
 it('rejects out-of-bounds or incomplete initial write counts before commit',async()=>{for(const result of [{parentInserts:2,versionInserts:1,pointerUpdates:1},{parentInserts:1,versionInserts:0,pointerUpdates:1}]){const s=fixture();f.db=Object.assign(async()=>[{db:'tutorial_staging_cf_20260908',role:'tutorial_staging',result}],{unsafe:s.db.unsafe,end:s.db.end});await expect(promoteSingleThumbnail(s.plan,async()=>[])).rejects.toThrow('result_count');expect(s.calls).toContain('ROLLBACK');expect(s.calls).not.toContain('COMMIT')}});
});
