export const VERIFIED_37_SOFTWARES = [
  "Airtable",
  "BambooHR",
  "Brevo",
  "Calendly",
  "Canva",
  "ClickUp",
  "Deel",
  "Dext",
  "DocuSign",
  "Figma",
  "Framer",
  "Gusto",
  "Hotjar",
  "HubSpot",
  "Intercom",
  "Klaviyo",
  "Looker Studio",
  "Loom",
  "Make",
  "Miro",
  "Monday.com",
  "n8n",
  "Notion",
  "PandaDoc",
  "Pipedrive",
  "QuickBooks",
  "Remote.com",
  "Rippling",
  "Semrush",
  "Slack",
  "TradingView",
  "Typeform",
  "Webex",
  "Webflow",
  "Xero",
  "Zapier",
  "Zendesk",
] as const;

export type VerifiedSoftware = (typeof VERIFIED_37_SOFTWARES)[number];
