import {describe,expect,it} from 'vitest';
import {planProceduralLayout,proceduralTemplateMatches,safeProceduralTemplate} from '../procedural-layout-planner.js';

describe('procedural thumbnail layout planner',()=>{
 it('gives one short word a dominant single hitbox',()=>{const p=planProceduralLayout({lines:['RESET'],hasUiScreenshot:true,variantIndex:0});expect(p.strategy).toBe('single-hero');expect(p.wordCount).toBe(1);expect(p.template.headlineHeight).toBe(218);expect(p.template.hostSide).toBe('right')});
 it('allocates more stacking height to long translated words',()=>{const p=planProceduralLayout({lines:['DATEN JETZT WIEDERHERSTELLEN'],hasUiScreenshot:true,variantIndex:2});expect(p.strategy).toBe('long-word-stack');expect(p.wordLengths).toContain('long');expect(p.template.headlineHeight).toBe(310)});
 it('opens a recovery layout for four-word localized copy without collapsing the UI',()=>{const p=planProceduralLayout({lines:['DÉSACTIVER LA SAUVEGARDE AUTOMATIQUE'],hasUiScreenshot:true,variantIndex:2});expect(p.template.headlineHeight).toBe(400);expect(p.template.uiY).toBeGreaterThanOrEqual(p.template.headlineY+p.template.headlineHeight);expect(p.template.uiHeight).toBeGreaterThanOrEqual(240)});
 it('never admits more than four words into geometry decisions',()=>expect(planProceduralLayout({lines:['ONE TWO THREE FOUR FIVE SIX'],hasUiScreenshot:false,variantIndex:0}).wordCount).toBe(4));
 it('varies face scale logo size and edge position deterministically',()=>{const a=planProceduralLayout({lines:['UPLOAD FIX'],hasUiScreenshot:true,variantIndex:0}).template,b=planProceduralLayout({lines:['UPLOAD FIX'],hasUiScreenshot:true,variantIndex:1}).template;expect([a.hostScale,a.logoSize,a.hostEdgeOffset]).not.toEqual([b.hostScale,b.logoSize,b.hostEdgeOffset])});
 it('supports a deliberate left-host plan without changing the default',()=>{const left=planProceduralLayout({lines:['FIND FILE'],hasUiScreenshot:true,variantIndex:0,hostSide:'left'}).template;expect(left.hostSide).toBe('left');expect(left.uiX).toBeGreaterThan(500);expect(planProceduralLayout({lines:['FIND FILE'],hasUiScreenshot:true,variantIndex:0}).template.hostSide).toBe('right')});
 it('admits custom templates only for their word count language and length pattern',()=>{const base=planProceduralLayout({lines:['FIX DRIVE'],hasUiScreenshot:true,variantIndex:0}).template;const template={...base,appliesToWordCounts:[2],languages:['de'],wordLengthPattern:'short-long' as const};expect(proceduralTemplateMatches(template,['FIX WIEDERHERSTELLUNG'],'de')).toBe(true);expect(proceduralTemplateMatches(template,['WIEDERHERSTELLUNG FIX'],'de')).toBe(false);expect(proceduralTemplateMatches(template,['FIX WIEDERHERSTELLUNG'],'en')).toBe(false);expect(proceduralTemplateMatches(template,['FIX'],'de')).toBe(false)});
 it('clamps every visible hitbox inside the canvas',()=>{const raw=planProceduralLayout({lines:['FIX'],hasUiScreenshot:true,variantIndex:0}).template;const safe=safeProceduralTemplate({...raw,headlineX:1200,uiY:700,logoX:1270,arrowY:710});expect(safe.headlineX+safe.headlineWidth).toBeLessThanOrEqual(1280);expect(safe.uiY+safe.uiHeight).toBeLessThanOrEqual(720);expect(safe.logoX+safe.logoSize).toBeLessThanOrEqual(1280);expect(safe.arrowY+safe.arrowSize).toBeLessThanOrEqual(720)});
 it('keeps automatic text logo and UI geometry on the declared safe boundary',()=>{for(const hostSide of ['left','right'] as const){const t=planProceduralLayout({lines:['DÉSACTIVER LA SAUVEGARDE AUTOMATIQUE'],hasUiScreenshot:true,variantIndex:0,hostSide}).template;expect(t.headlineY).toBeGreaterThanOrEqual(36);expect(t.logoX).toBeGreaterThanOrEqual(36);expect(t.logoX+t.logoSize).toBeLessThanOrEqual(1244);expect(t.uiX).toBeGreaterThanOrEqual(36);expect(t.uiX+t.uiWidth).toBeLessThanOrEqual(1244);expect(t.uiY+t.uiHeight).toBeLessThanOrEqual(684)}});
});
