#!/usr/bin/env tsx
/**
 * Seed: Video Essay (Clip-Based) Template + Clip Library Config
 *
 * Creates a VIDEO_ESSAY template for long-form analysis videos (Star Wars history,
 * disturbing corporate practices, technology deep-dives, etc.) that uses real
 * video clips sourced from YouTube or MP4 uploads rather than AI-generated images.
 *
 * Pipeline:
 *   SCRIPTING → ASSET_COLLECTION → CLIP_SELECTION → [AWAITING_CLIP_REVIEW] →
 *   QMS_VALIDATING → ROUTING_RENDER → RENDERING_REMOTION → AWAITING_QC
 *
 * Script generation: Google Gemini API (primary) — set GEMINI_API_KEY in .env
 * Render: Remotion OffthreadVideo (clip-remotion workflow)
 *   - Single encode pass, no generational quality loss
 *   - Source video quality preserved until final output
 *
 * Asset Requirements:
 *   - audio/tts: AI33 TTS narration
 *   - Clips come from clip library (not tracked in r2_asset_manifest)
 *
 * Usage:
 *   pnpm --filter @repo/db seed:video-essay-clip
 */

import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { contentTemplates } from "./schema/content-templates.js";
import { clipLibraries, clipLibraryConfigs } from "./schema/index.js";
import { eq } from "drizzle-orm";
import { config } from "dotenv";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
config({ path: resolve(__dirname, "../../../.env") });

import { loadConfig, getConfig } from "@repo/config";

async function seed() {
  loadConfig();
  const { DATABASE_URL } = getConfig();
  const sql = postgres(DATABASE_URL);
  const db = drizzle(sql);

  // ── 1. Template ────────────────────────────────────────────────────────────
  const templateName = "Video Essay (Clip-Based)";

  const templateData = {
    name: templateName,
    description:
      "Long-form video essay format. Uses AI33 TTS narration over real video clips sourced from YouTube or MP4 uploads. Script generated by Claude. Rendered with Remotion OffthreadVideo for single-pass, lossless quality.",
    format: "VIDEO_ESSAY" as const,

    pipeline_stages: [
      "SCRIPTING",
      "ASSET_COLLECTION",
      "CLIP_SELECTION",
      "QMS_VALIDATING",
      "ROUTING_RENDER",
      "RENDERING_REMOTION",
      "AWAITING_QC",
    ],

    prompts: {
      script: `You are a scriptwriter for a long-form video essay channel.

Write a compelling, deeply researched video essay script on the following topic: \${topic}

Requirements:
- 2500-4000 words (approximately 15-25 minutes of speaking time at 150 WPM)
- Tone: authoritative, engaging, intellectually curious — you take the audience seriously
- Structure: Hook → Historical/contextual background → Core thesis → Evidence and examples → Counterarguments → Synthesis → Closing reflection
- Continuous prose suitable for spoken delivery — no bullet points, no headers
- Each paragraph forms a natural visual scene (3-5 sentences)
- Build narrative tension throughout — this is not a Wikipedia article, it's a story
- End paragraphs with beats that invite the next thought

Output the script text only. No stage directions, no [brackets], no metadata.`,
    },

    render_config: {
      engine: "REMOTION" as const,
      workflow: "clip-remotion",
      settings: {
        fps: 30,
        width: 1920,
        height: 1080,
      },
      captions_enabled: true,
    },

    required_assets: ["audio/tts"],

    metadata: {
      pipeline_config: {
        script_provider: "claude",
        tts_provider: "ai33",
        shot_list_model: "claude-sonnet-4-6",
        no_tts: false,
        needs_scene_analysis: false,
        awaiting_va_after_automated: false,
      },
    },

    is_active: true,
  };

  const [existingTemplate] = await db
    .select({ id: contentTemplates.id })
    .from(contentTemplates)
    .where(eq(contentTemplates.name, templateName))
    .limit(1);

  let templateId: string;

  if (existingTemplate) {
    await db
      .update(contentTemplates)
      .set(templateData as any)
      .where(eq(contentTemplates.id, existingTemplate.id));
    templateId = existingTemplate.id;
    console.log(`[seed] Updated template: ${templateName} (${templateId})`);
  } else {
    const [inserted] = await db
      .insert(contentTemplates)
      .values(templateData as any)
      .returning({ id: contentTemplates.id });
    templateId = inserted!.id;
    console.log(`[seed] Created template: ${templateName} (${templateId})`);
  }

  // ── 2. Clip Library ───────────────────────────────────────────────────────
  const libraryName = "Video Essay Source Clips";

  const libraryData = {
    name: libraryName,
    slug: "video-essay-source-clips",
    description:
      "Source clip library for video essay format. Add source videos via /clip-library using YouTube URLs or MP4 uploads.",
    storage_strategy: "inline" as const,
    tag_vocabulary: {
      mood: [
        "serious",
        "dramatic",
        "educational",
        "archival",
        "newsreel",
        "documentary",
        "corporate",
        "political",
      ],
      location: [
        "office",
        "outdoors",
        "studio",
        "archive",
        "courtroom",
        "factory",
        "street",
        "generic",
      ],
      action: [
        "talking",
        "presenting",
        "working",
        "signing",
        "marching",
        "reacting",
        "idle",
      ],
      era: [
        "1940s",
        "1950s",
        "1960s",
        "1970s",
        "1980s",
        "1990s",
        "2000s",
        "2010s",
        "modern",
      ],
      custom: [
        "b-roll",
        "interview",
        "cutaway",
        "archival-footage",
        "news-clip",
        "reenactment",
      ],
    },
  };

  const [existingLibrary] = await db
    .select({ id: clipLibraries.id })
    .from(clipLibraries)
    .where(eq(clipLibraries.name, libraryName))
    .limit(1);

  let libraryId: string;

  if (existingLibrary) {
    await db
      .update(clipLibraries)
      .set(libraryData as any)
      .where(eq(clipLibraries.id, existingLibrary.id));
    libraryId = existingLibrary.id;
    console.log(`[seed] Updated clip library: ${libraryName} (${libraryId})`);
  } else {
    const [inserted] = await db
      .insert(clipLibraries)
      .values(libraryData as any)
      .returning({ id: clipLibraries.id });
    libraryId = inserted!.id;
    console.log(`[seed] Created clip library: ${libraryName} (${libraryId})`);
  }

  // ── 3. Clip Library Config (format-level, channel-agnostic) ───────────────
  const [existingConfig] = await db
    .select({ id: clipLibraryConfigs.id })
    .from(clipLibraryConfigs)
    .where(eq(clipLibraryConfigs.format, "VIDEO_ESSAY"))
    .limit(1);

  const configData = {
    format: "VIDEO_ESSAY" as const,
    channel_id: null,
    clip_library_id: libraryId,
    clip_selection_enabled: true,
    hitl_clip_review: false,
    clips_per_sentence: 1,
    min_gap_before_repeat: 8,
    character_continuity: "off" as const,
    broll_fallback_enabled: false,
    broll_fallback_model: null,
    playbook: {
      format: "VIDEO_ESSAY",
      system_prompt_addendum:
        "Select clips that directly illustrate the spoken content. Prefer archival footage, news clips, and documentary-style shots. Match the emotional weight of the narration. Avoid repeated use of the same clip within 8 positions. For long-form topics, prefer clips that establish context before cutting to detail shots.",
      preferred_shot_scales: ["wide", "medium", "close"],
      avoid_audio_classes: ["music_only", "silence"],
      character_continuity: "off",
      clips_per_sentence: 1,
      min_clip_duration_ms: 1500,
      max_clip_duration_ms: 12000,
      transition_style: "cut",
      music_volume: 0,
      music_ducking_volume: 0,
      visual_mode: "full_screen",
    },
  };

  if (existingConfig) {
    await db
      .update(clipLibraryConfigs)
      .set(configData as any)
      .where(eq(clipLibraryConfigs.id, existingConfig.id));
    console.log(
      `[seed] Updated clip library config for VIDEO_ESSAY (${existingConfig.id})`,
    );
  } else {
    const [inserted] = await db
      .insert(clipLibraryConfigs)
      .values(configData as any)
      .returning({ id: clipLibraryConfigs.id });
    console.log(
      `[seed] Created clip library config for VIDEO_ESSAY (${inserted!.id})`,
    );
  }

  await sql.end();
  console.log("\n[seed] Done.");
  console.log(
    "\nTo use: create a job with the 'Video Essay (Clip-Based)' template.",
  );
  console.log(
    "Add source videos via /clip-library (YouTube URL or MP4 upload) before running clip selection.",
  );
  console.log(
    "Ensure ANTHROPIC_API_KEY is set in .env for Claude script generation.",
  );
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
