import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import {
  TUTORIAL_UPLOADER_JOB_VERSION,
  TutorialUploaderJobSchema,
  TutorialUploaderReceiptSchema,
  canonicalTutorialUploaderJob,
  tutorialUploaderReceiptFileName,
  type TutorialUploaderJob,
} from "../tutorial-uploader-exchange";

function job(): TutorialUploaderJob {
  return {
    version: TUTORIAL_UPLOADER_JOB_VERSION,
    job_id: "2096fe21-44ae-4a2a-9251-573c84b9e85f",
    revision: 1,
    idempotency_key: "tutorial-studio:2096fe21:1",
    created_at: "2026-09-01T20:00:00.000Z",
    operation: "upload",
    channel_id: "tutorial_usa",
    target_video_id: null,
    assets: [
      {
        key: "video",
        role: "video",
        file_name: "video.mp4",
        size_bytes: 100,
        sha256: "a".repeat(64),
        media_type: "video/mp4",
      },
      {
        key: "thumbnail",
        role: "thumbnail",
        file_name: "thumbnail.jpg",
        size_bytes: 20,
        sha256: "b".repeat(64),
        media_type: "image/jpeg",
      },
    ],
    attributes: {
      title: "A real title",
      description: "Description",
      tags: ["tutorial"],
      visibility: "private",
      made_for_kids: false,
      monetization: "on",
      ad_suitability: "none",
    },
  };
}

describe("tutorial uploader exchange contract", () => {
  it("serializes jobs canonically with sorted object keys", () => {
    const canonical = canonicalTutorialUploaderJob(job());
    expect(canonical.startsWith('{"assets":')).toBe(true);
    expect(canonical.endsWith('"version":"tutorial-uploader-job/1"}')).toBe(
      true,
    );
    // Golden value generated by uploader_contracts.exchange.ExchangeJob.sha256().
    expect(createHash("sha256").update(canonical).digest("hex")).toBe(
      "d2be7f39c4378999a0153798aff1650e5c6956c60fd16130f973837b7617d55f",
    );
  });

  it("normalizes the zero-millisecond timestamp like the Python consumer", () => {
    expect(TutorialUploaderJobSchema.parse(job()).created_at).toBe(
      "2026-09-01T20:00:00Z",
    );
  });

  it("requires exactly one video and one thumbnail", () => {
    const value = job();
    value.assets[1] = { ...value.assets[0]!, key: "video_two" };
    expect(TutorialUploaderJobSchema.safeParse(value).success).toBe(false);
  });

  it("refuses monetization without an explicit suitability declaration", () => {
    const value = job();
    delete value.attributes.ad_suitability;
    expect(TutorialUploaderJobSchema.safeParse(value).success).toBe(false);
  });

  it("refuses tags that the direct executor would silently rewrite", () => {
    const value = job();
    value.attributes.tags = ["bad, tag"];
    expect(TutorialUploaderJobSchema.safeParse(value).success).toBe(false);
  });

  it("validates and names immutable success receipts", () => {
    const receipt = TutorialUploaderReceiptSchema.parse({
      version: "tutorial-uploader-receipt/1",
      job_id: job().job_id,
      revision: 1,
      idempotency_key: job().idempotency_key,
      manifest_sha256: "c".repeat(64),
      sequence: 8,
      state: "succeeded",
      occurred_at: "2026-09-01T21:04:00.000Z",
      progress: 1,
      message: "verified",
      result: {
        video_id: "AbCdEfGhI_1",
        video_url: "https://www.youtube.com/watch?v=AbCdEfGhI_1",
        applied_attributes: ["title", "description", "thumbnail"],
        proof_ref: "proofs/verified.json",
      },
      error: null,
    });
    expect(tutorialUploaderReceiptFileName(receipt)).toBe(
      `${job().job_id}.r1.${"c".repeat(12)}.s000008.succeeded.json`,
    );
  });

  it("refuses unknown applied attributes in receipts", () => {
    const parsed = TutorialUploaderReceiptSchema.safeParse({
      version: "tutorial-uploader-receipt/1",
      job_id: job().job_id,
      revision: 1,
      idempotency_key: job().idempotency_key,
      manifest_sha256: "c".repeat(64),
      sequence: 1,
      state: "succeeded",
      occurred_at: "2026-09-01T21:04:00.000Z",
      progress: 1,
      message: "verified",
      result: {
        video_id: "AbCdEfGhI_1",
        video_url: "https://youtu.be/AbCdEfGhI_1",
        applied_attributes: ["made_up"],
        proof_ref: "proofs/verified.json",
      },
      error: null,
    });
    expect(parsed.success).toBe(false);
  });
});
