import type { Job } from "bullmq";
import { execFile } from "node:child_process";
import { mkdir, unlink, rename } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import type { StockLibraryGenPayload } from "@repo/contracts";
import { StockLibraryGenPayloadSchema } from "@repo/contracts";
import type { DrizzleClient } from "@repo/db";
import {
  markStockClipFailed,
  markStockClipGenerating,
  markStockClipReady,
  storeClipEmbedding,
} from "@repo/db/repositories";
import { eq } from "drizzle-orm";
import { stockClips } from "@repo/db";
import {
  requestVideoFromText,
  downloadMedia,
} from "../../utils/media-gateway/index.js";
import { embedBatch } from "../../utils/gemini-embed.js";

const execFileAsync = promisify(execFile);
const FFMPEG_BIN = process.env["FFMPEG_PATH"] ?? "ffmpeg";
const FFPROBE_BIN = process.env["FFPROBE_PATH"] ?? "ffprobe";
const STOCK_LIB_DIR =
  process.env["STOCK_LIBRARY_DIR"] ?? "/opt/content-forge/media/stock-library";

async function probeDurationSec(path: string): Promise<number> {
  const { stdout } = await execFileAsync(
    FFPROBE_BIN,
    [
      "-v",
      "error",
      "-show_entries",
      "format=duration",
      "-of",
      "default=noprint_wrappers=1:nokey=1",
      path,
    ],
    { maxBuffer: 64 * 1024 * 1024 },
  );
  return parseFloat(stdout.trim());
}

/**
 * Re-encode VEO output to a known-good x264 mp4 with stripped audio
 * (the library is silent-only — narration is added at assembly time)
 * and a constant 25 fps. Without this the assembler hits frame-rate
 * mismatches across stock clips from different generation runs.
 */
async function normaliseClip(
  rawPath: string,
  finalPath: string,
): Promise<void> {
  await execFileAsync(
    FFMPEG_BIN,
    [
      "-y",
      "-i",
      rawPath,
      "-vf",
      "scale=1920:1080:force_original_aspect_ratio=decrease:flags=lanczos," +
        "pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,fps=25,format=yuv420p",
      "-c:v",
      "libx264",
      "-preset",
      "veryfast",
      "-crf",
      "20",
      "-an",
      "-movflags",
      "+faststart",
      finalPath,
    ],
    { maxBuffer: 64 * 1024 * 1024 },
  );
}

export function createStockLibraryGenProcessor(db: DrizzleClient) {
  return async (job: Job<StockLibraryGenPayload>) => {
    const { stockClipId } = StockLibraryGenPayloadSchema.parse(job.data);

    // Load the reserved row so we have the prompt + vibe_tag.
    const [row] = await db
      .select()
      .from(stockClips)
      .where(eq(stockClips.id, stockClipId))
      .limit(1);
    if (!row) throw new Error(`stock_clip ${stockClipId} not found`);
    if (row.status === "ready") {
      // Already generated by a previous worker — nothing to do.
      return;
    }

    await mkdir(STOCK_LIB_DIR, { recursive: true });
    const rawPath = join(STOCK_LIB_DIR, `${stockClipId}.raw.mp4`);
    const finalPath = join(STOCK_LIB_DIR, `${stockClipId}.mp4`);

    try {
      // Request video through the unified media gateway (forge primary,
      // fastgen fallback while it lives).
      await markStockClipGenerating(stockClipId, "media-gateway");

      const videoRef = await requestVideoFromText(row.prompt, {
        format: "STOCK_LIBRARY",
        context: `stock_clip:${stockClipId}`,
        maxWaitMs: 600_000, // 10 minutes max
      });

      // Download the video to local storage
      await downloadMedia(videoRef, rawPath);

      // Normalize to h264/25fps mp4
      await normaliseClip(rawPath, finalPath);
      await unlink(rawPath).catch(() => {});

      const dur = await probeDurationSec(finalPath);
      await markStockClipReady(stockClipId, finalPath, dur);
      console.log(
        JSON.stringify({
          level: "info",
          message: "Stock clip ready",
          stock_clip_id: stockClipId,
          duration_sec: dur,
          vibe_tag: row.vibe_tag,
          provider: "media-gen",
        }),
      );
      // Fire-and-forget: embed the prompt so the semantic matcher can use
      // this clip immediately. Non-blocking — a failure here is logged but
      // does not fail the job; the clip falls back to random selection until
      // the next batch embed run picks it up.
      embedBatch([row.prompt])
        .then(([vec]) => {
          if (vec) return storeClipEmbedding(stockClipId, vec);
        })
        .catch((err: unknown) => {
          console.warn(
            JSON.stringify({
              level: "warn",
              message: "stock clip embed failed (non-fatal)",
              stock_clip_id: stockClipId,
              error: err instanceof Error ? err.message : String(err),
            }),
          );
        });
    } catch (err) {
      await unlink(rawPath).catch(() => {});
      await unlink(finalPath).catch(() => {});
      const attemptsLeft =
        (job.opts.attempts ?? 1) - ((job.attemptsMade ?? 0) + 1);
      const isFinal = attemptsLeft <= 0;
      if (isFinal) {
        await markStockClipFailed(stockClipId).catch(() => {});
      }
      console.warn(
        JSON.stringify({
          level: "warn",
          message: "Stock clip generation failed",
          stock_clip_id: stockClipId,
          attempts_left: attemptsLeft,
          error: err instanceof Error ? err.message : String(err),
        }),
      );
      throw err;
    }

    // Make TS happy about unused import in trivial branches.
    void rename;
  };
}
