/** Read-only exact-one thumbnail/archive diagnostic. Private paths stay in memory. */
import {execFileSync} from 'node:child_process';
const job='48790ac0-6ad1-4ce6-8ac4-7f7c26c428a6';
function ssh(host:string,command:string,input:string){return execFileSync('ssh',['-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10',host,command],{input,encoding:'utf8',timeout:45000,maxBuffer:1024*1024,stdio:['pipe','pipe','pipe']});}
try{
  if(process.argv.length!==2)throw Error('read_only');
  const base=`'thumbnails',(SELECT coalesce(json_agg(x),'[]') FROM (SELECT id,language,status,is_selected,review_verdict,output_path FROM thumbnails WHERE subject_id='${job}'::uuid) x),'artifacts',(SELECT coalesce(json_agg(x),'[]') FROM (SELECT id,vps_path,state,drive_file_id,verified_at,bytes,checksum_sha256 FROM storage_artifacts WHERE owner_kind='tutorial_job' AND kind='thumbnail' AND job_id='${job}'::uuid) x)`;
  const target=JSON.parse(ssh('vps2','docker exec -i tutorial-recovery-staging-postgres-1 psql -X -U tutorial_staging -d tutorial_staging_cf_20260908 -qAt -v ON_ERROR_STOP=1',`BEGIN READ ONLY;SELECT json_build_object(${base},'versions',(SELECT coalesce(json_agg(v),'[]') FROM storage_artifact_versions v JOIN storage_artifacts a ON a.id=v.artifact_id WHERE a.owner_kind='tutorial_job' AND a.kind='thumbnail' AND a.job_id='${job}'::uuid));ROLLBACK;`));
  const source=JSON.parse(ssh('cf-vps-deploy','docker exec -i content-forge-postgres psql -X -U postgres -d content_forge -qAt -v ON_ERROR_STOP=1',`BEGIN READ ONLY;SELECT json_build_object(${base});ROLLBACK;`));
  const selected=target.thumbnails.filter((t:any)=>t.is_selected&&['en','english'].includes(t.language.toLowerCase()));
  const sourceSelected=source.thumbnails.filter((t:any)=>t.is_selected&&['en','english'].includes(t.language.toLowerCase()));
  const paths=selected.map((t:any)=>({id:t.id,path:t.output_path}));
  function fileScript(items:any[]){return `const fs=require('node:fs');const out=${JSON.stringify(items)}.map(x=>{if(typeof x.path!=='string'||!x.path.startsWith('/opt/content-forge/media/'))return{id:x.id,safeRoot:false,exists:false};try{const s=fs.lstatSync(x.path);return{id:x.id,safeRoot:true,exists:true,regular:s.isFile()&&!s.isSymbolicLink(),bytes:s.size}}catch(e){if(e.code==='ENOENT')return{id:x.id,safeRoot:true,exists:false};return{id:x.id,safeRoot:true,unreadable:true}}});process.stdout.write(JSON.stringify(out));`;}
  const targetFiles=JSON.parse(ssh('vps2','docker exec -i --user 1000:1000 tutorial-recovery-staging-web-1 node',fileScript(paths)));
  const sourceFiles=JSON.parse(ssh('cf-vps-deploy','node',fileScript(sourceSelected.map((t:any)=>({id:t.id,path:t.output_path})))));
  const report=selected.map((t:any)=>({thumbnailId:t.id,status:t.status,reviewVerdict:t.review_verdict,outputPathPresent:!!t.output_path,local:targetFiles.find((x:any)=>x.id===t.id),currentMappings:target.artifacts.map((a:any)=>({artifactId:a.id,pathMatches:a.vps_path===t.output_path,state:a.state,driveId:a.drive_file_id,verified:!!a.verified_at,bytes:a.bytes,sha256:a.checksum_sha256})),matchingVersionCount:target.versions.filter((v:any)=>v.vps_path===t.output_path).length,verifiedMatchingVersions:target.versions.filter((v:any)=>v.vps_path===t.output_path&&v.drive_file_id&&v.verified_at&&v.bytes&&v.checksum_sha256).map((v:any)=>({artifactId:v.artifact_id,driveId:v.drive_file_id,bytes:v.bytes,sha256:v.checksum_sha256}))}));
  console.log(JSON.stringify({jobId:job,selectedEnglishCount:selected.length,thumbnailRows:target.thumbnails.length,report,sourceSelected:sourceSelected.map((t:any)=>({thumbnailId:t.id,status:t.status,local:sourceFiles.find((x:any)=>x.id===t.id),matchingArchiveCount:source.artifacts.filter((a:any)=>a.vps_path===t.output_path&&a.drive_file_id&&a.verified_at).length})),databaseWrites:0,downloads:0}));
}catch{console.log(JSON.stringify({stopped:true,detailsWithheld:true,databaseWrites:0,downloads:0}));process.exitCode=1;}
