/** Exact singleton directory prerequisite; explicit reviewed one-directory apply only. */
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
const options=['-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=10'];
function ssh(command:string,input:string){return execFileSync('ssh',[...options,'vps2',command],{input,encoding:'utf8',timeout:30000,maxBuffer:1024*1024,stdio:['pipe','pipe','pipe']})}
try{
const apply=process.argv.length===3&&process.argv[2]==='--create-reviewed-single';if(!(process.argv.length===2||apply))throw Error('explicit_mode');
const path=JSON.parse(ssh('node',`const f=require('node:fs'),c=require('node:crypto'),p='/var/tmp/tutorial-single-thumbnail-70175471-10ac-4d26-81d5-da503701b942/manifest.json',s=f.lstatSync(p);if(!s.isFile()||s.isSymbolicLink()||s.uid!==0||(s.mode&0o077)||s.size>16384)throw Error('private_manifest');const raw=f.readFileSync(p,'utf8');if(c.createHash('sha256').update(raw).digest('hex')!=='b4b5585e49e2822b0bdd24a4d907184de40c3f041725ab6fcb63b0255064467c')throw Error('manifest_changed');process.stdout.write(JSON.stringify(JSON.parse(raw).sourcePath));`));
const module=Buffer.from(readFileSync('scripts/migration/prepare-media-directories.mjs','utf8')).toString('base64');
const code=`const {lstat}=await import('node:fs/promises'),{createHash}=await import('node:crypto');if(process.getuid()!==1000)throw Error('uid');for(const p of ['/opt','/opt/content-forge','/opt/content-forge/media']){const s=await lstat(p);if(!s.isDirectory()||s.isSymbolicLink())throw Error('root');}const m=await import('data:text/javascript;base64,${module}'),p=await m.planDirectories([${JSON.stringify(path)}]);const hash=createHash('sha256').update(JSON.stringify(p)).digest('hex');let created=0;
if(${apply}){if(hash!=='340218f241921ec8a19fcdd4de38d3e8978f635bf57a8aeba86cbf944425db08'||p.safePaths!==1||p.unsafe.length||Object.keys(p.blocked).length||JSON.stringify(p.create)!==JSON.stringify(['/opt/content-forge/media/thumbnails/48790ac0-6ad1-4ce6-8ac4-7f7c26c428a6']))throw Error('reviewed_plan_changed');created=await m.applyDirectories(p);const s=await lstat(p.create[0]);if(!s.isDirectory()||s.isSymbolicLink()||s.uid!==1000||(s.mode&0o777)!==0o700)throw Error('created_directory_guard');}
const after=await m.planDirectories([${JSON.stringify(path)}]);process.stdout.write(JSON.stringify({safePaths:p.safePaths,existingDirectories:p.existing,plannedDirectories:p.create.length,relativeDirectories:p.create.map(s=>s.slice(m.MEDIA_ROOT.length+1)),blockedDirectories:p.unsafe.length,blockedPaths:p.blocked,planHash:hash,createdDirectories:created,afterPlannedDirectories:after.create.length,databaseWrites:0,mediaFilesWritten:0}));`;
console.log(ssh('docker exec -i --user 1000:1000 tutorial-recovery-staging-web-1 node --input-type=module',code));
}catch{console.log(JSON.stringify({stopped:true,createdDirectories:process.argv.includes('--create-reviewed-single')?null:0,databaseWrites:0}));process.exitCode=1;}
