import {describe,it,expect} from 'vitest';
import {TutorialChannelProfileSchema as S,channelProfileConflict,configuredTutorialThumbnailMode,resolveTutorialChannelTargets} from '@repo/contracts';
const primary={id:'11111111-1111-4111-8111-111111111111',is_primary:true,language:'en',metadata:{}},child={id:'22222222-2222-4222-8222-222222222222',is_primary:false,language:'ja',metadata:{}};
describe('explicit channel groups',()=>{
 it('new channels never automatically translate',()=>{const p=S.parse({});expect(p.translationEnabled).toBe(false);expect(p.primaryChannelId).toBeNull()});
 it('starts with right-locked UI-first thumbnails and exposes their per-channel controls',()=>{const p=S.parse({});expect(p.proceduralLayoutIds).toEqual(['ui-card-host-right','icon-focus-host-right']);expect(p.proceduralUiScreenshot).toBe(true);expect(p.proceduralTheme).toBe('light-first');expect(p.proceduralArrow).toBe(true);expect(p.proceduralLogoTreatment).toBe('badge');expect(p.proceduralLogoAura).toBe(false);expect(p.proceduralLogoAuraOpacity).toBe(.28);expect(p.proceduralTemplates).toEqual([])});
 it('stores deliberate cross-video left-host templates with translation-safe hitboxes',()=>{const p=S.parse({proceduralTemplates:[{id:'44444444-4444-4444-8444-444444444444',name:'Left host · long words',hostSide:'left',headlineWidth:640,auraEnabled:true,auraOpacity:.2,appliesToWordCounts:[2,3],wordLengthPattern:'contains-long',languages:['de'],headlineLines:'3'}]});expect(p.proceduralTemplates[0]).toMatchObject({hostSide:'left',headlineWidth:640,headlineHeight:224,uiWidth:700,logoSize:152,auraEnabled:true,auraOpacity:.2,appliesToWordCounts:[2,3],wordLengthPattern:'contains-long',languages:['de'],headlineLines:'3'})});
 it('supports arbitrary existing voice languages and independent overrides',()=>{const p=S.parse({primaryChannelId:primary.id,translationEnabled:true,thumbnailMode:'ai',promptOverrides:{metadata:'Japanese channel instructions'}});expect(channelProfileConflict(child,p,[primary,child])).toBeNull();expect(p.promptOverrides.metadata).toBe('Japanese channel instructions')});
 it('rejects invalid and cyclic group ownership',()=>{expect(()=>S.parse({translationEnabled:true})).toThrow();expect(channelProfileConflict(primary,S.parse({primaryChannelId:child.id}),[primary,child])).not.toBeNull()});
 it('rejects duplicate locale destinations per primary',()=>{const p=S.parse({primaryChannelId:primary.id});expect(channelProfileConflict(child,p,[primary,{...child,id:'33333333-3333-4333-8333-333333333333',metadata:{tutorialChannelProfile:p}}])).toContain('already')});
 it('rejects foreign URLs and reference selection without host',()=>{expect(()=>S.parse({youtubeUrl:'https://evil.test/@name'})).toThrow();expect(()=>S.parse({referenceImageIds:[child.id]})).toThrow()});
 it('keeps enabled and no-translation contradictory states invalid',()=>expect(()=>S.parse({primaryChannelId:primary.id,translationEnabled:true,translationMethod:'none'})).toThrow());
 it('distinguishes explicit thumbnail workflow settings from legacy defaults',()=>{expect(configuredTutorialThumbnailMode({})).toBeUndefined();expect(configuredTutorialThumbnailMode({tutorialChannelProfile:{thumbnailMode:'ai'}})).toBe('ai');expect(configuredTutorialThumbnailMode({tutorialChannelProfile:{thumbnailMode:'manual'}})).toBeUndefined()});
 it('resolves arbitrary locales only through explicit enabled child profiles',()=>{const p=S.parse({primaryChannelId:primary.id,translationEnabled:true});expect(resolveTutorialChannelTargets(primary.id,[{id:primary.id,language:'en',isPrimary:true,enabled:true,metadata:{}},{id:child.id,language:'ja',isPrimary:false,enabled:true,metadata:{tutorialChannelProfile:p}},{id:'33333333-3333-4333-8333-333333333333',language:'es',isPrimary:false,enabled:true,metadata:{}}]).targets.map(target=>target.language)).toEqual(['ja'])});
 it('blocks duplicate destinations instead of picking one',()=>{const p=S.parse({primaryChannelId:primary.id,translationEnabled:true});const resolved=resolveTutorialChannelTargets(primary.id,[{id:child.id,language:'ja',isPrimary:false,enabled:true,metadata:{tutorialChannelProfile:p}},{id:'33333333-3333-4333-8333-333333333333',language:'ja',isPrimary:false,enabled:true,metadata:{tutorialChannelProfile:p}}]);expect(resolved.targets).toEqual([]);expect(resolved.blocked[0]?.language).toBe('ja')});
});
