import type { NextRequest } from "next/server";
import { eq, inArray } from "drizzle-orm";
import {
  createCfRawRenderQueue,
  createCfFinishingRenderQueue,
  createRedisConnection,
} from "@repo/queue";
import { withApiAuth } from "../../../../_lib/auth";
import { db } from "@/lib/db";
import { cfFinishingVariants, cfRawClips, cfSources } from "@repo/db";
import { getHubConfig } from "@/lib/config";
import { statArtifacts } from "../../../_lib/artifacts";

export const dynamic = "force-dynamic";

/** Hard ceiling on one batch so a mis-click can't queue thousands of renders. */
const MAX_BATCH = 200;

interface Body {
  /**
   * "missing" (default) — only rebuild what has no playable MP4 on disk.
   * "all"                — rebuild every clip of the source from scratch.
   */
  scope?: "missing" | "all";
  /** Optional cap on the number of raw clips touched. */
  limit?: number;
}

/**
 * POST /api/v1/clip-forge/sources/:id/render-all
 *
 * Batch render for a whole source. Producing clips at volume was impossible
 * before this existed: the console could only re-render ONE variant at a time,
 * so a source with 61 mined clips needed 61+ manual clicks, and there was no
 * way at all to rebuild raw clips whose files had been deleted.
 *
 * Two independent repairs, both driven off the filesystem rather than the DB:
 *
 *   1. Raw clips whose `raw_mp4_key` has no file on disk are re-enqueued on
 *      CF_RAW_RENDER. That processor also regenerates finishing variants, so
 *      one enqueue rebuilds the whole subtree for that clip.
 *   2. Clips whose raw MP4 is fine but which own variant rows with missing
 *      `rendered_mp4_key` files get a targeted CF_FINISHING_RENDER per
 *      variant — no need to redo the (expensive) raw trim.
 *
 * Returns exact counts so the UI reports what it actually did.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: sourceId } = await params;
  return withApiAuth(req, async () => {
    const body = (await req.json().catch(() => ({}))) as Body;
    const scope = body.scope === "all" ? "all" : "missing";
    const limit = Math.min(
      MAX_BATCH,
      Math.max(1, Number(body.limit) || MAX_BATCH),
    );

    const [source] = await db
      .select()
      .from(cfSources)
      .where(eq(cfSources.id, sourceId))
      .limit(1);
    if (!source) {
      return new Response(JSON.stringify({ error: "source not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Cancelled clips are excluded on purpose: the operator rejected them and
    // a batch rebuild must not resurrect them.
    const clips = await db
      .select()
      .from(cfRawClips)
      .where(eq(cfRawClips.source_id, sourceId));
    const candidates = clips.filter(
      (c) => c.status !== "cancelled" && !c.cancel_requested,
    );

    const rawStats = await statArtifacts(candidates.map((c) => c.raw_mp4_key));
    const needRawRender =
      scope === "all"
        ? candidates
        : candidates.filter(
            (c) => !(c.raw_mp4_key && rawStats.get(c.raw_mp4_key)?.present),
          );
    const rawToQueue = needRawRender.slice(0, limit);
    const rawIds = new Set(rawToQueue.map((c) => c.id));

    // Variants belonging to clips we are NOT re-rendering wholesale — those
    // would be regenerated by raw-render anyway, so queueing them here would
    // just double the work.
    const otherClipIds = candidates
      .map((c) => c.id)
      .filter((id) => !rawIds.has(id));
    const variants = otherClipIds.length
      ? await db
          .select({
            id: cfFinishingVariants.id,
            key: cfFinishingVariants.rendered_mp4_key,
          })
          .from(cfFinishingVariants)
          .where(inArray(cfFinishingVariants.raw_clip_id, otherClipIds))
      : [];
    const variantStats = await statArtifacts(variants.map((v) => v.key));
    const variantsToQueue = (
      scope === "all"
        ? variants
        : variants.filter((v) => !(v.key && variantStats.get(v.key)?.present))
    ).slice(0, MAX_BATCH);

    const cfg = getHubConfig();
    const conn = createRedisConnection({ url: cfg.REDIS_URL, mode: "queue" });
    try {
      if (rawToQueue.length > 0) {
        const q = createCfRawRenderQueue(conn);
        try {
          await q.addBulk(
            rawToQueue.map((c) => ({
              name: "cf-raw-render",
              data: { raw_clip_id: c.id },
            })),
          );
        } finally {
          await q.close();
        }
      }
      if (variantsToQueue.length > 0) {
        const q = createCfFinishingRenderQueue(conn);
        try {
          await q.addBulk(
            variantsToQueue.map((v) => ({
              name: "cf-finishing-render",
              data: { variant_id: v.id },
            })),
          );
        } finally {
          await q.close();
        }
      }
    } finally {
      await conn.quit().catch(() => {});
    }

    return {
      scope,
      clips_total: candidates.length,
      raw_renders_queued: rawToQueue.length,
      raw_renders_skipped_already_present:
        candidates.length - needRawRender.length,
      variant_renders_queued: variantsToQueue.length,
      truncated: needRawRender.length > rawToQueue.length,
    };
  });
}
