"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
type Policy = { mode: "manual" | "scheduled_automatic"; notMadeForKidsConfirmed: boolean; monetization?: "on" | "off"; adSuitabilityConfirmed: boolean };
const initial: Policy = { mode: "manual", notMadeForKidsConfirmed: false, adSuitabilityConfirmed: false };
type Channel = { id: string; name: string; language: string; policy: Policy | null };
export function ChannelDeliveryPolicy({channelId}:{channelId?:string}={}) {
  const [channels, setChannels] = useState<Channel[]>([]); const [canManage, setCanManage] = useState(false);
  const [id, setId] = useState(""); const [policy, setPolicy] = useState<Policy>(initial); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetch("/api/production/channel-delivery-policy").then(response => response.json()).then(data => { setCanManage(Boolean(data.canManage)); setChannels(data.channels ?? []); }).catch(() => undefined); }, []);
  useEffect(()=>{if(channelId&&channels.some(c=>c.id===channelId)){setId(channelId);setPolicy(channels.find(c=>c.id===channelId)?.policy??initial)}},[channelId,channels]);
  if (!canManage) return null;
  const save = async () => { setSaving(true); try { const response = await fetch("/api/production/channel-delivery-policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ channelId: id, policy }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Policy save failed"); setChannels(previous => previous.map(channel => channel.id === id ? { ...channel, policy } : channel)); toast.success("Channel delivery policy saved. Existing external schedules were not cancelled."); } catch (error) { toast.error(error instanceof Error ? error.message : "Policy save failed"); } finally { setSaving(false); } };
  return <details style={{ padding: 12, border: "1px solid var(--v2-border-1)", borderRadius: 8 }}><summary>Admin · Automatic delivery after final approval</summary>
    <p>Manual by default. Opt in separately for each primary/language channel. Recovery queues approved assets and reserved slots without depending on the VA keeping a page open. A compatible live uploader must still claim them; this setting does not itself publish.</p>
    <select aria-label="Automatic delivery channel" value={id} disabled={saving} onChange={event => { setId(event.target.value); setPolicy(channels.find(channel => channel.id === event.target.value)?.policy ?? initial); }} style={{ padding: 8, color: "var(--v2-text-1)", background: "var(--v2-surface-2)" }}><option value="">Choose a channel</option>{channels.map(channel => <option key={channel.id} value={channel.id}>{channel.name} · {channel.language}</option>)}</select>
    {id && <fieldset disabled={saving} style={{ display: "grid", gap: 10, marginTop: 12 }}><label>After final approval <select aria-label="Automatic delivery mode" value={policy.mode} onChange={event => setPolicy(previous => ({ ...previous, mode: event.target.value as Policy["mode"] }))}><option value="manual">Manual delivery / explicit queue click</option><option value="scheduled_automatic">Automatically queue scheduled delivery</option></select></label>
      {policy.mode === "scheduled_automatic" && <><label><input type="checkbox" checked={policy.notMadeForKidsConfirmed} onChange={event => setPolicy(previous => ({ ...previous, notMadeForKidsConfirmed: event.target.checked }))} /> I confirm this channel's automatically queued tutorials are not made for kids.</label><label>Monetization <select aria-label="Automatic delivery monetization" value={policy.monetization ?? ""} onChange={event => setPolicy(previous => ({ ...previous, monetization: event.target.value ? event.target.value as "on" | "off" : undefined }))}><option value="">Choose explicitly</option><option value="off">Off</option><option value="on">On</option></select></label>{policy.monetization === "on" && <label><input type="checkbox" checked={policy.adSuitabilityConfirmed} onChange={event => setPolicy(previous => ({ ...previous, adSuitabilityConfirmed: event.target.checked }))} /> I confirm no ad-suitability issues for automatically queued tutorials on this channel.</label>}</>}
      <button type="button" onClick={() => void save()}>{saving ? "Saving…" : "Save delivery policy"}</button><small>Disabling holds unclaimed automatic requests and prevents new ones. Use emergency pause to stop all new admissions. Videos already scheduled externally are not cancelled.</small></fieldset>}
  </details>;
}
