import {
  pgTable,
  uuid,
  text,
  varchar,
  timestamp,
  numeric,
  index,
} from "drizzle-orm/pg-core";

/**
 * Pre-generated generic drama clips that get randomly chained into
 * the body of LONG_FORM_DRAMA STOCK_CHAIN_* videos. The library is
 * grown by the stock-library-gen worker and by writeback of hook
 * clips from STOCK_CHAIN_HOOKED renders.
 */
export const stockClips = pgTable(
  "stock_clips",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Absolute path on the VPS (e.g. /opt/content-forge/media/stock-library/<uuid>.mp4)
    // or R2 key once we move to R2 storage.
    video_path: text("video_path").notNull(),
    // ffprobed at insert time; the picker uses this to know slot bounds.
    duration_sec: numeric("duration_sec", { precision: 6, scale: 3 }).notNull(),
    // The prompt that generated this clip. For debug + future regeneration.
    prompt: text("prompt").notNull(),
    // Optional human-readable tag (e.g. 'apartment_b_roll', 'argument').
    // Not used by the picker in v1 — random ignores it.
    vibe_tag: varchar("vibe_tag", { length: 64 }),
    // VEO traceability.
    veo_job_id: text("veo_job_id"),
    // Which library this clip belongs to. NULL during migration window
    // for rows that pre-date the introduction of clip_libraries; new
    // rows MUST be scoped to a library so cross-channel reuse is
    // explicit and not accidental.
    clip_library_id: uuid("clip_library_id"),
    // 'queued' | 'generating' | 'ready' | 'failed'
    status: varchar("status", { length: 16 }).notNull().default("queued"),
    // 'bootstrap' (generated by the library-gen worker) | 'hook_writeback'
    // (originally a hook clip from a STOCK_CHAIN_HOOKED render).
    origin: varchar("origin", { length: 24 }).notNull().default("bootstrap"),
    created_at: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    // Touched whenever the clip is used in a video. Used to bias the
    // picker toward less-used clips.
    last_used_at: timestamp("last_used_at", { withTimezone: true }),
  },
  (t) => ({
    statusIdx: index("stock_clips_status_idx").on(t.status),
    lastUsedIdx: index("stock_clips_last_used_at_idx").on(t.last_used_at),
    libraryIdx: index("stock_clips_library_idx").on(t.clip_library_id),
  }),
);

/**
 * Many-to-many of which stock clips were used in which content_job.
 * Lets us answer 'which clips did this video use' for debugging without
 * polluting drama_clips with an FK to stock_clips.
 */
export const stockClipUses = pgTable(
  "stock_clip_uses",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    job_id: uuid("job_id").notNull(),
    stock_clip_id: uuid("stock_clip_id")
      .notNull()
      .references(() => stockClips.id, { onDelete: "cascade" }),
    // 0-indexed position within this job's clip chain.
    position: numeric("position", { precision: 6, scale: 0 }).notNull(),
    created_at: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => ({
    jobIdx: index("stock_clip_uses_job_idx").on(t.job_id),
    clipIdx: index("stock_clip_uses_clip_idx").on(t.stock_clip_id),
  }),
);
