import { z } from "zod";

/**
 * V2 Composition Plan — Biome-Based Layout System (Sentence-Level)
 *
 * Layouts persist for stretches of sentences (biomes) with bell-curve durations
 * and adjacency compatibility rules. This is NOT random per-sentence selection.
 *
 * Architecture:
 * - Sentences are the atomic video timing unit
 * - Layouts span multiple sentences (biome logic)
 * - Paragraphs are LLM context only (for image prompt generation)
 *
 * Layout frequency hierarchy:
 * - AVATAR_PIP: ~55% (dominant, average 4 sentences per biome)
 * - AVATAR_SPLIT: ~20% (50:50 split, average 2-3 sentences)
 * - AVATAR_FULLSCREEN: ~10-12% (narrator only, 2-5 sentences)
 * - QUOTE_CARD: content-gated (1 sentence only)
 * - IMAGE_FULLSCREEN: rare (1-2 sentences for dramatic B-roll)
 */

export const LayoutTypeSchema = z.enum([
  "AVATAR_PIP",
  "AVATAR_FULLSCREEN",
  "AVATAR_SPLIT",
  "QUOTE_CARD",
  "IMAGE_FULLSCREEN",
]);

export type LayoutType = z.infer<typeof LayoutTypeSchema>;

export const TransitionTypeSchema = z.enum([
  "CUT",
  "CROSSFADE",
  "DIP_TO_BLACK",
]);

export type TransitionType = z.infer<typeof TransitionTypeSchema>;

/**
 * A biome is a contiguous stretch of sentences sharing the same layout.
 * Generated by the domain-layer biome algorithm, not per-sentence randomization.
 */
export const BiomeEntrySchema = z.object({
  layoutType: LayoutTypeSchema,
  startSentenceIndex: z.number().int().nonnegative(),
  endSentenceIndex: z.number().int().nonnegative().describe("Inclusive"),
  transitionIn: TransitionTypeSchema,
});

export type BiomeEntry = z.infer<typeof BiomeEntrySchema>;

/**
 * Per-sentence entry derived from the biome sequence.
 * Each sentence knows its layout and whether it's the first in its biome
 * (which determines if a transition animation should be applied).
 */
export const CompositionPlanEntrySchema = z.object({
  sentenceIndex: z.number().int().nonnegative().describe("Global sentence index across all paragraphs"),
  sceneIndex: z.number().int().nonnegative().describe("Which paragraph (scene) this sentence belongs to"),
  layoutType: LayoutTypeSchema,
  isFirstInBiome: z.boolean().describe("True = apply transition animation"),
  transitionIn: TransitionTypeSchema,
  avatarSide: z
    .enum(["left", "right"])
    .optional()
    .describe("For AVATAR_SPLIT: which side the avatar appears on"),
  isHook: z
    .boolean()
    .describe("True = sentence is in the hook zone, image prompts should spark curiosity"),
});

export type CompositionPlanEntry = z.infer<typeof CompositionPlanEntrySchema>;

/**
 * Complete composition plan for a V2 render.
 * Stored in assembly_manifest.composition_plan.
 */
export const CompositionPlanSchema = z.object({
  entries: z.array(CompositionPlanEntrySchema).min(1),
  biomes: z.array(BiomeEntrySchema).min(1),
  masterSeed: z.number().int(),
  hookEndSentenceIndex: z.number().int().nonnegative(),
  outroStartSentenceIndex: z.number().int().nonnegative(),
});

export type CompositionPlan = z.infer<typeof CompositionPlanSchema>;
