/** Synthetic, provider-free local fixture and atomic-approval HTTP probe. */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import postgres from "postgres";
import { signToken } from "../apps/hub-web/src/lib/auth/jwt";
const require = createRequire(new URL("../apps/hub-web/package.json", import.meta.url));
const sharp = require("sharp");
if (process.env.DATABASE_URL !== "postgresql://recovery:local-test-only@127.0.0.1:55438/tutorial_recovery_test" || process.env.JWT_SECRET !== "local-recovery-test-secret-not-for-production-2026") throw new Error("Exact local DB and JWT required");
const sql = postgres(process.env.DATABASE_URL, { max: 1 });
const root = randomUUID();
const mediaRoot = "C:/Users/konra/AppData/Local/Temp/tutorial-recovery-media";
try {
  const [owner] = await sql`SELECT id FROM users WHERE email='va@recovery.test'`;
  const [other] = await sql`SELECT id FROM users WHERE email='other@recovery.test'`;
  assert(owner && other);
  for (const language of ["en", "de", "fr", "it", "sv"]) {
    const [channel] = await sql`SELECT id FROM channels WHERE youtube_channel_id=${`recovery-test-${language}`}`; assert(channel);
    await sql`INSERT INTO tutorial_jobs(id,created_by,source_job_id,channel_id,title,mode,status,script_provider,tts_provider,tts_voice,language,thumbnail_text_top,thumbnail_text_bottom,script_text)
      VALUES(${language === "en" ? root : randomUUID()},${owner.id},${language === "en" ? null : root},${channel.id},${`SYNTHETIC AI CHOICE TEST ${language} ${root.slice(0,8)}`},'THREE_MIN','AWAITING_THUMBNAILS','test','test','test',${language},'SYNTHETIC TEST',${`OPTION ${language.toUpperCase()}`},'Synthetic prewritten script. No provider invocation.')`;
  }
  const [channel] = await sql`SELECT channel_id FROM tutorial_jobs WHERE id=${root}`;
  const ids: string[] = []; await mkdir(join(mediaRoot, "thumbnails"), { recursive: true });
  for (let index = 0; index < 5; index++) {
    const id = randomUUID(); ids.push(id);
    const path = join(mediaRoot, "thumbnails", `${id}.png`);
    const svg = `<svg width="1280" height="720"><rect width="1280" height="720" fill="#172033"/><text x="70" y="220" fill="white" font-size="70" font-family="sans-serif">SYNTHETIC API / UI TEST</text><text x="70" y="360" fill="#ffe349" font-size="90" font-family="sans-serif">OPTION ${index + 1}</text><text x="70" y="560" fill="white" font-size="36" font-family="sans-serif">Not generated by a provider. Not for publication.</text></svg>`;
    await writeFile(path, await sharp(Buffer.from(svg)).png().toBuffer(), { flag: "wx" });
    await sql`INSERT INTO thumbnails(id,subject_kind,subject_id,channel_id,language,prompt_mode,prompt_used,status,output_path,is_selected,review_verdict,generation_kind,variant_index,provider_used) VALUES(${id},'tutorial_job',${root},${channel!.channel_id},'en','manual','Synthetic fixture only','completed',${path},false,'not_reviewed','variant',${index},'synthetic-test')`;
  }
  console.log(JSON.stringify({ sourceJobId: root, candidateIds: ids, locales: 4, imageFiles: 5, providerCalls: 0, state: "unapproved", url: `http://127.0.0.1:3108/thumbnails?tab=composer&jobId=${root}&language=en` }));
  if (process.argv.includes("--http")) {
    const token = await signToken({ userId: owner.id, email: "va@recovery.test", role: "TUTORIAL_VA" });
    const otherToken = await signToken({ userId: other.id, email: "other@recovery.test", role: "TUTORIAL_VA" });
    const choose = (auth = token) => fetch(`http://127.0.0.1:3108/api/production/jobs/${root}/thumbnail/ai/choose`, { method: "POST", headers: { Cookie: `hub_session=${auth}`, "Content-Type": "application/json" }, body: JSON.stringify({ thumbnailId: ids[0] }) });
    assert.equal((await choose(otherToken)).status, 403);
    const first = await choose(); assert.equal(first.status, 200, await first.clone().text());
    assert.equal((await choose()).status, 200);
    const fanout = await sql`SELECT source_thumbnail_id,state,target_language,source_sha256,source_size FROM tutorial_thumbnail_fanout WHERE source_job_id=${root}`;
    assert.equal(fanout.length, 4); assert(fanout.every(row => row.source_thumbnail_id === ids[0] && row.state === "pending" && row.source_sha256.length === 64 && row.source_size > 0));
    const selected = await sql`SELECT id,review_verdict FROM thumbnails WHERE subject_id=${root} AND is_selected`; assert.equal(selected.length, 1); assert.equal(selected[0]!.id, ids[0]); assert.equal(selected[0]!.review_verdict, "acceptable");
    const [job] = await sql`SELECT va_review_status FROM tutorial_jobs WHERE id=${root}`; assert.notEqual(job!.va_review_status, "approved");
    console.log(JSON.stringify({ clickApproval: true, duplicateClickIdempotent: true, exactImageFanoutIntents: 4, crossVaBlocked: true, notPublicationApproved: true, providerCalls: 0 }));
    const [child] = await sql`SELECT id,channel_id FROM tutorial_jobs WHERE source_job_id=${root} AND language='de'`;
    const localizedId = randomUUID();
    const [englishImage] = await sql`SELECT output_path FROM thumbnails WHERE id=${ids[0]!}`;
    await sql`INSERT INTO thumbnails(id,subject_kind,subject_id,channel_id,language,prompt_mode,prompt_used,status,output_path,is_selected,review_verdict,generation_kind) VALUES(${localizedId},'tutorial_job',${child!.id},${child!.channel_id},'de','programmatic','Synthetic prior localized output','completed',${englishImage!.output_path},true,'acceptable','localize')`;
    await sql`UPDATE tutorial_jobs SET publication_approval=${sql.json({ synthetic: true })},va_review_status='approved' WHERE id=${child!.id}`;
    const replacement = await fetch(`http://127.0.0.1:3108/api/production/jobs/${root}/thumbnail/ai/choose`, { method: "POST", headers: { Cookie: `hub_session=${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ thumbnailId: ids[1] }) });
    assert.equal(replacement.status, 200, await replacement.clone().text());
    const [invalidated] = await sql`SELECT is_selected,review_verdict,output_path FROM thumbnails WHERE id=${localizedId}`;
    assert.equal(invalidated!.is_selected, false); assert.equal(invalidated!.review_verdict, "not_reviewed"); assert.equal(invalidated!.output_path, englishImage!.output_path);
    const [childState] = await sql`SELECT publication_approval,va_review_status FROM tutorial_jobs WHERE id=${child!.id}`; assert.equal(childState!.publication_approval, null); assert.equal(childState!.va_review_status, null);
    console.log(JSON.stringify({ replacementEnglishInvalidatesLocaleSelection: true, localePublicationReceiptCleared: true, priorBytesPreserved: true, providerCalls: 0 }));
    const failedId = randomUUID();
    await sql`INSERT INTO thumbnails(id,subject_kind,subject_id,channel_id,language,prompt_mode,prompt_used,status,is_selected,review_verdict,generation_kind,provider_used) VALUES(${failedId},'tutorial_job',${root},${channel!.channel_id},'en','programmatic','Synthetic ambiguous provider failure','failed',false,'not_reviewed','variant','synthetic-test')`;
    const retry = await fetch(`http://127.0.0.1:3108/api/production/jobs/${root}/thumbnail/ai`, { method: "POST", headers: { Cookie: `hub_session=${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ requestId: randomUUID(), retryThumbnailId: failedId, top: "SYNTHETIC TEST", bottom: "NO PAID RETRY" }) });
    assert.equal(retry.status, 409, await retry.clone().text());
    assert.equal((await retry.json()).code, "ADMIN_RECONCILIATION_REQUIRED");
    const retryBatches = await sql`SELECT request_id FROM tutorial_thumbnail_ai_batches WHERE job_id=${root}`;
    assert.equal(retryBatches.length, 0);
    console.log(JSON.stringify({ ambiguousEnglishRetryBlocked: true, noNewPaidBatch: true, providerCalls: 0 }));
  }
} finally { await sql.end(); }
