import { strict as assert } from "node:assert";
import { randomUUID } from "node:crypto";
import postgres from "postgres";
import { createDrizzleClient, createOrReuseTutorialJob } from "../packages/db/dist/index.js";
const url = process.env.DATABASE_URL;
if (url !== "postgresql://recovery:local-test-only@127.0.0.1:55438/tutorial_recovery_test") throw new Error("Only isolated recovery DB allowed");
const db = createDrizzleClient(url); const client = postgres(url);
const [owner] = await client`SELECT id FROM users WHERE email='va@recovery.test'`;
const [other] = await client`SELECT id FROM users WHERE email='other@recovery.test'`;
const [channel] = await client`SELECT id FROM channels WHERE name='Test tutorials en'`;
assert(owner && other && channel);
const data = { created_by: owner.id, channel_id: channel.id, keyword_ref: `intake-test-${randomUUID()}`, title: "Intake concurrency fixture", mode: "THREE_MIN" as const, status: "QUEUED" as const, script_provider: "test", tts_provider: "test", tts_voice: "test" };
const results = await Promise.all(Array.from({ length: 12 }, () => createOrReuseTutorialJob(db, data)));
assert.equal(results.filter((row) => row.created).length, 1);
assert.equal(new Set(results.map((row) => row.job?.id)).size, 1);
assert.equal((await createOrReuseTutorialJob(db, { ...data, created_by: other.id })).job, null);
const id = results[0].job!.id;
await client`UPDATE tutorial_jobs SET status='FAILED_SCRIPT' WHERE id=${id}`;
const retry = await createOrReuseTutorialJob(db, data);
assert.equal(retry.created, false); assert.equal(retry.job?.id, id); assert.equal(retry.job?.status, "FAILED_SCRIPT");
await client`UPDATE tutorial_jobs SET status='CANCELLED' WHERE id=${id}`;
await client`UPDATE tutorial_keyword_outbox SET delivered_at=now(),last_error='Local test only' WHERE tutorial_job_id=${id}`;
await client.end();
console.log(JSON.stringify({ concurrentRequests: 12, created: 1, ownerConflictBlocked: true, failureRetryPreservesIdentity: true, externalCalls: 0 }));
process.exit(0);
