/**
 * @repo/queue - Queue Infrastructure
 *
 * Public exports for the queue package.
 * Provides typed BullMQ queue and worker factories.
 */

// Queue name constants
export { QUEUE_NAMES } from "./constants/queue-names.js";
export type { QueueName } from "./constants/queue-names.js";

// Connection factory
export { createRedisConnection, closeRedisConnection } from "./connection.js";
export type { RedisConnectionOptions } from "./connection.js";

// Queue options
export {
  ingestQueueOptions,
  aiGenerationQueueOptions,
  assetCollectionQueueOptions,
  qmsValidationQueueOptions,
  renderHeavyQueueOptions,
  garbageCollectionQueueOptions,
  sceneAnalysisQueueOptions,
  autoLabelQueueOptions,
  deadLetterQueueOptions,
  clipIngestQueueOptions,
  clipLabelQueueOptions,
  clipEmbedQueueOptions,
  clipSelectionQueueOptions,
  clipRetagQueueOptions,
  clipExtractQueueOptions,
  dramaTTSQueueOptions,
  dramaTranscribeQueueOptions,
  dramaPromptGenQueueOptions,
  dramaImageGenQueueOptions,
  dramaVideoGenQueueOptions,
  dramaAssembleQueueOptions,
  dramaQCQueueOptions,
  dramaThumbnailQueueOptions,
  thumbnailQueueOptions,
  tutorialGenerateQueueOptions,
  tutorialSpliceQueueOptions,
  tutorialStitchQueueOptions,
  reactorDownloadQueueOptions,
  reactorTranscribeQueueOptions,
  reactorScriptQueueOptions,
  reactorTTSQueueOptions,
  reactorAssembleQueueOptions,
  getQueueOptions,
} from "./options/queue-options.js";

// Worker options
export {
  ingestWorkerOptions,
  aiGenerationWorkerOptions,
  assetCollectionWorkerOptions,
  qmsValidationWorkerOptions,
  renderHeavyWorkerOptions,
  garbageCollectionWorkerOptions,
  sceneAnalysisWorkerOptions,
  autoLabelWorkerOptions,
  deadLetterWorkerOptions,
  clipIngestWorkerOptions,
  clipLabelWorkerOptions,
  clipEmbedWorkerOptions,
  clipSelectionWorkerOptions,
  clipRetagWorkerOptions,
  clipExtractWorkerOptions,
  dramaTTSWorkerOptions,
  dramaTranscribeWorkerOptions,
  dramaPromptGenWorkerOptions,
  dramaImageGenWorkerOptions,
  dramaVideoGenWorkerOptions,
  dramaAssembleWorkerOptions,
  dramaQCWorkerOptions,
  dramaThumbnailWorkerOptions,
  thumbnailWorkerOptions,
  tutorialGenerateWorkerOptions,
  tutorialSpliceWorkerOptions,
  tutorialStitchWorkerOptions,
  reactorDownloadWorkerOptions,
  reactorTranscribeWorkerOptions,
  reactorScriptWorkerOptions,
  reactorTTSWorkerOptions,
  reactorAssembleWorkerOptions,
  getWorkerOptions,
} from "./options/worker-options.js";

// Queue factories
export {
  createIngestQueue,
  createAIGenerationQueue,
  createAssetCollectionQueue,
  createQMSValidationQueue,
  createRenderHeavyQueue,
  createGarbageCollectionQueue,
  createSceneAnalysisQueue,
  createAutoLabelQueue,
  createDeadLetterQueue,
  createBundestagClipAnalysisQueue,
  createBundestagPlaybookGenerationQueue,
  createBundestagRenderQueue,
  createVideoStitchQueue,
  createClipIngestQueue,
  createClipLabelQueue,
  createClipLabelBatchQueue,
  createClipEmbedQueue,
  createImageIngestQueue,
  createImageLabelQueue,
  createImageEmbedQueue,
  createClipSelectionQueue,
  createClipRetagQueue,
  createClipExtractQueue,
  createDramaTTSQueue,
  createDramaTranscribeQueue,
  createDramaPromptGenQueue,
  createDramaImageGenQueue,
  createDramaVideoGenQueue,
  createDramaAssembleQueue,
  createDramaQCQueue,
  createDramaThumbnailQueue,
  createThumbnailQueue,
  createStockLibraryGenQueue,
  createTutorialGenerateQueue,
  createTutorialSpliceQueue,
  createTutorialStitchQueue,
  createReactorDownloadQueue,
  createReactorTranscribeQueue,
  createReactorScriptQueue,
  createReactorTTSQueue,
  createReactorAssembleQueue,
  createCfIngestQueue,
  createCfClipDetectionQueue,
  createCfRawRenderQueue,
  createCfFinishingRenderQueue,
  createTechFootageCollectionQueue,
} from "./factories/queue-factories.js";

// Worker factories
export {
  createIngestWorker,
  createAIGenerationWorker,
  createAssetCollectionWorker,
  createQMSValidationWorker,
  createRenderHeavyWorker,
  createGarbageCollectionWorker,
  createSceneAnalysisWorker,
  createAutoLabelWorker,
  createDeadLetterWorker,
  createBundestagClipAnalysisWorker,
  createBundestagPlaybookGenerationWorker,
  createBundestagRenderWorker,
  createClipIngestWorker,
  createClipLabelWorker,
  createClipLabelBatchWorker,
  createClipEmbedWorker,
  createImageIngestWorker,
  createImageLabelWorker,
  createImageEmbedWorker,
  createClipSelectionWorker,
  createClipRetagWorker,
  createClipExtractWorker,
  createDramaTTSWorker,
  createDramaTranscribeWorker,
  createDramaPromptGenWorker,
  createDramaImageGenWorker,
  createDramaVideoGenWorker,
  createDramaAssembleWorker,
  createDramaQCWorker,
  createDramaThumbnailWorker,
  createThumbnailWorker,
  createStockLibraryGenWorker,
  createTutorialGenerateWorker,
  createTutorialSpliceWorker,
  createTutorialStitchWorker,
  createReactorDownloadWorker,
  createReactorTranscribeWorker,
  createReactorScriptWorker,
  createReactorTTSWorker,
  createReactorAssembleWorker,
  createCfIngestWorker,
  createCfClipDetectionWorker,
  createCfRawRenderWorker,
  createCfFinishingRenderWorker,
  createTechFootageCollectionWorker,
} from "./factories/worker-factories.js";
export type { Processor } from "./factories/worker-factories.js";

// Event helpers
export {
  attachStandardEventListeners,
  attachProgressEventListener,
  attachAllEventListeners,
} from "./events/event-helpers.js";

export const QUEUE_PACKAGE_VERSION = "0.1.0";
