import { chromium } from "playwright";
const base = "http://212.132.103.168";
const b = await chromium.launch();
const p = await b.newPage();
const bad = [];
p.on("response", (r) => { if (r.status() >= 400) bad.push(r.status() + " " + r.url()); });
await p.goto(base + "/login", { waitUntil: "networkidle" });
await p.fill("#email", "omar@tutorialstudio.app");
await p.fill("#password", "Omar-Ts26-9f4K");
await Promise.all([p.waitForURL((u)=>!u.toString().includes("/login"),{timeout:20000}).catch(()=>{}), p.click('button:has-text("Sign In")')]);
await p.waitForTimeout(1000);
await p.goto(base + "/thumbnails", { waitUntil: "networkidle" });
await p.getByText("PERSONAS",{exact:false}).first().click().catch(()=>{});
await p.waitForTimeout(1500);
await p.mouse.wheel(0, 4000); await p.waitForTimeout(1500);
console.log(bad.length ? bad.join("\n") : "NO 4xx");
await b.close();
